
// Auth Action Types
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const REQUEST_CHECK_AUTH = 'REQUEST_CHECK_AUTH';

// Examiner Action Types
export const REQUEST_GET_EXAMINERS = 'REQUEST_GET_EXAMINERS';
export const REQUEST_CREATE_EXAMINER = 'REQUEST_CREATE_EXAMINER';
export const REQUEST_UPDATE_EXAMINER = 'REQUEST_UPDATE_EXAMINER';
export const REQUEST_DELETE_EXAMINER = 'REQUEST_DELETE_EXAMINER';

// Exam Action Types
export const REQUEST_GET_EXAMS = 'REQUEST_GET_EXAMS';
export const REQUEST_GET_MY_EXAMS = 'REQUEST_GET_MY_EXAMS';
export const REQUEST_CREATE_EXAM = 'REQUEST_CREATE_EXAM';
export const REQUEST_UPDATE_EXAM = 'REQUEST_UPDATE_EXAM';
export const REQUEST_DELETE_EXAM = 'REQUEST_DELETE_EXAM';

// Settings Action Types
export const REQUEST_GET_SETTINGS = 'REQUEST_GET_SETTINGS';
export const REQUEST_UPDATE_SETTINGS = 'REQUEST_UPDATE_SETTINGS';

// Candidate Action Types
export const REQUEST_GET_CANDIDATES = 'REQUEST_GET_CANDIDATES';
export const REQUEST_CREATE_CANDIDATE = 'REQUEST_CREATE_CANDIDATE';
export const REQUEST_UPDATE_CANDIDATE = 'REQUEST_UPDATE_CANDIDATE';
export const REQUEST_DELETE_CANDIDATE = 'REQUEST_DELETE_CANDIDATE';
